import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/global/Navbar";
import Footer from "@/components/global/Footer";
import Member from "@/components/global/Member"
import { createBackground } from "./lib/createBackground" 
import { BackgroundProvider } from "./lib/backgroundContext"
import GlobalBackground from "../components/global/GlobalBackground"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BackgroundProvider>
          <GlobalBackground />
          <Member />
          <Navbar />
          {children}
          <Footer />
        </BackgroundProvider>
      </body>
    </html>
  );
}
